language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - if [[ -n $TRAVIS_TAG ]]; then unset BUILD_TAG TWINE_REPOSITORY_URL ]]; fi
  - python setup.py egg_info -b "$BUILD_TAG" sdist bdist_wheel
  - pip install dist/*.whl
  - pip install flake8 twine

script:
  - twine check dist/*
  - flake8

jobs:
  include:
    - stage: deploy
      name: Upload release to PyPI
      if: tag is present OR branch = test-deploy
      script: twine upload dist/*.tar.gz dist/*.whl
      env:
        - BUILD_TAG=dev$TRAVIS_BUILD_NUMBER
        - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
        - TWINE_USERNAME=coldfix-deploy
        # TWINE_PASSWORD:
        - secure: "O5qJFgdE84J340e/H3AG1N4nZt7nY5a8CSsBQUYeguCrcWKI2vn/BafcNBMveLZMmaePjXvAiVcC43yvh25/LyDJYx6G5PTqmFHrTOoRoDRkwCo0vBc2ImgFrdMHwQZfyxDzzaEChdqTRFQg8f+E2OeAW0Ou/Fh0OHJMI0j8acJhEIuXhuZt5wTJ9ZEIiIjcwr24TpdwUe3CByk65CHsCqHBC6kvhUEt8eC1ujQXgg8oTg6IG4sCFT29hfAjdE0peJpPAKV9Zx9aSUSR9h3tY3pA9zVFb88jsXZrvJ0D8+5fdj+k7q6N63sw/vBLdvwG6XZnMv54dh6T6r2a/9J9+vhB4zF2pKGVw0Xm/mSCRjeMmKP2BLGqvlsr64V6qjuWjNRP6/dxXrh2JfIa5vgaFnDn1SH1OimjcN3sfNN9RpHWaxVQIR/9ZLu9TKiLr8ozj0An48pUZ1vTDkAd0FRYljDjZA9GcXsDYfxpcE4rfpltnK1o5Q5ncO7JQhr6LznWPfeBu+Y0dL7cQAy6h1D9AjJwDExbM+HASpegDBaydEAP/666x9xFv+JkzcKdQV4coLfgGDEivsB6CFx+n3vA+9WIOFJ7utp0Z9TcKaQUwiPzlxMV4ulVpMRZX63k5Rrhvul/A7EsIDT9KZ5aesJhuIFRb+pyaBP8y79KKORl5aw="
